<?php
/**
 * @file
 * Include the only file of the library.
 *
 * There are 5-6 funcs there and their names are not prefixed.
 * But these names are quite unprobable to cause collisions...
 */

if (!function_exists('str_get_html')) {
  $simplehtmldom_library_path = _simplhtmldom_get_library_path();
  if (!empty($simplehtmldom_library_path)) {
    require_once $simplehtmldom_library_path;
  }
}
else {
  drupal_set_message(t('The simplehtmldom API module found that you define its functions before it does itself! Somewhere in your drupal files there must be a copy of the simplehtmldom PHP library that you do not need if you have this drupal module... Please remove the old library and live happily. The simplehtmldom module will include the necessary php files from the lib as soon as you remove the old ones.'), 'error');
}

/**
 * Returns path of simplhtmldom library.
 *
 * @return bool|string
 *   Path to library.
 */
function _simplhtmldom_get_library_path() {

  $file = 'simple_html_dom.php';
  $library = 'simplehtmldom';
  // Support libraries module.
  if (module_exists('libraries') && file_exists(libraries_get_path($library) . "/$file")) {
    return libraries_get_path($library) . "/$file";
  }
  else {
    $paths = array(
      'sites/all/libraries/' . $library,
      drupal_get_path('module', 'simplehtmldom') . '/' . $library,
      drupal_get_path('module', 'simplehtmldom') . "/libraries",
      'profiles/' . variable_get('install_profile', 'default') . '/libraries/' . $library,
    );
    foreach ($paths as $library_path) {
      $path = $library_path . "/$file";
      if (file_exists($path)) {
        return $path;
      }
    }
  }
  return FALSE;
}
